/*
 * This source file was generated by the Gradle 'init' task
 */
package com.company;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.*;

public class CalculatorTest {

    private Calculator calculator;

    @BeforeClass
    public static void setupBeforeAllTests() {
        System.out.println("Before all tests: Initializing shared resources.");
    }

    @AfterClass
    public static void cleanupAfterAllTests() {
        System.out.println("After all tests: Cleaning up shared resources.");
    }

    @Before
    public void setupBeforeEachTest() {
        calculator = new Calculator();
        System.out.println("Before each test: Creating new Calculator instance.");
    }

    @After
    public void cleanupAfterEachTest() {
        System.out.println("After each test: Test completed.");
    }

    @Test
    public void testAddition() {
        int result = calculator.add(2, 3);
        assertEquals("Addition should return 5", 5, result);
    }

    @Test
    public void testMultiplication() {
        int result = calculator.multiply(4, 5);
        assertEquals("Multiplication should return 20", 20, result);
    }

}
