/*
 * This source file was generated by the Gradle 'init' task
 */
package com.company;

public class Calculator {

    public int add(int a, int b) {
        return a + b;
    }

    public int multiply(int a, int b) {
        return a + b;
    }

}
